#!/usr/bin/env perl

use v5.14;
BEGIN {
    die "Need appledaily article URLs\n" unless @ARGV;
}

use utf8;
binmode STDOUT, ":utf8";

use FindBin;
use lib "$FindBin::Bin/lib";
use Ceis::Extractor;

my $extractor = Ceis::Extractor->new(
    wanted  => "p, .article_paragraph h1, .article_paragraph h2",
    exclude => qr/(讚一個|版權所有)/
);

for (@ARGV) {
    next unless m{tw\.nextmedia\.com/[^/]+/article};
    $extractor->url($_);

    say for $extractor->sentences;
}
