#!/usr/bin/env perl
use v5.14;
use strict;
use warnings;
use Data::Dumper;
use Hijk;

my $url = shift @ARGV or die "Usage: $0 \URL\n";;

my $archivers = [
    sub {
        my $res = Hijk::request({
            method => "GET",
            host   => "archive.today",
            port   => "80",
            path   => "/submit/",
            body   => "url=$url",
            parse_chunked => 1,
        });
        return $res;
    },
    sub {
        my $res = Hijk::request({
            method => "GET",
            host   => "web.archive.org",
            port   => "80",
            path   => "/save/$url",
            parse_chunked => 1,
        });
        return $res;
    },
];

for my $archiver (@$archivers) {
    my $kid = fork();
    unless ($kid) {
        my $res = $archiver->();
        say $res->{status}, " ", (substr( ($res->{status} =~ /^3/) ? $res->{head}{Location} : $res->{body} , 0, 64) =~ s/\n/\\n/gr);
        exit;
    }
}

wait() for @$archivers;
