#!/usr/bin/env perl

use v5.14;
use Bing::Search;
use Bing::Search::Source::Web;
use Term::ANSIColor;

$ENV{BING_SEARCH_APP_ID} or die "Need BING_SEARCH_APP_ID";
$ARGV[0] or die "Need ARGV[0]";

my $bing = Bing::Search->new();

$bing->AppId($ENV{BING_SEARCH_APP_ID});
$bing->Query($ARGV[0]);
$bing->add_source(Bing::Search::Source::Web->new);

for my $result (@{ $bing->search->results }) {
    say colored("title", "yellow") . " " . $result->Title;
    say colored("  url", "yellow") . " " . $result->Url;
    say "";
}
