#!/bin/sh

file=$1

if [[ ! -f $file ]]
then
    echo
    echo "blob-put <file>"
    echo
    exit 1
fi

if [[ ! -f ~/etc/blob.txt ]]
then
    echo
    echo "Prepare ~/etc/blob.txt like this:"
    echo
    echo "    echo s3://my-s3-bucket/prefx/ > ~/etc/blob.txt"
    echo
    exit 1
fi

s3prefix=$(cat ~/etc/blob.txt)

file_basename=$(basename $file)
file_shasum=$(shasum $file | cut -c 1-40)

s3full=${s3prefix}${file_shasum}/${file_basename}

s3cmd --continue-put put $file $s3full

echo "$file\t$s3full" >> ~/var/blob/index.$(echo $file_shasum | cut -c1,2).tsv
