#!/usr/bin/env perl
use v5.14;
use utf8;
binmode STDIN, ":utf8";
binmode STDOUT, ":utf8";

my @urls;
@urls = @ARGV if @ARGV;

if (@urls == 0) {
    use Regexp::Common qw/URI/;

    local $/ = undef;
    my $in = <STDIN>;
    @urls = $in =~ m/($RE{URI}{HTTP}{-scheme=>"https?"})/g;
}
else {
    utf8::decode($_) for(@urls);
}

use FindBin;
use lib "$FindBin::Bin/lib";
use Brain;

my $brain = Brain->new;

for my $url (@urls) {
    $brain->study($url);
    say "read: $url";
}

__END__

=begin USAGE

Pass URLs from argv:

   $0 URL URL...

Or pass URLs from STDIN:

   cat file-with-urls.txt | $0

=cut

