#!/usr/bin/env perl

use v5.14;
use FindBin;
use lib "$FindBin::Bin/lib";

use Brain;
use List::MoreUtils qw(natatime);

binmode STDIN, ":utf8";
binmode STDOUT, ":utf8";

undef $/;
$_ = <STDIN>;
s/\n//g;

my @sentences;
my $iter = natatime 2, split(/(:?。\」|！\」|。(?!\」))\n*/, $_);
while(my @vals = $iter->()) {
    push @sentences, join "", @vals;
}

my $brain = Brain->new;

for my $x (@sentences) {
    my $k = $brain->remember($x);
    say "Added: $k => $x";
}
