#!/usr/bin/env perl
use v5.14;
use utf8;
binmode STDIN, ":utf8";
binmode STDOUT, ":utf8";

my @urls;
@urls = @ARGV if @ARGV;

if ($urls[0] eq '-') {
    local $/ = undef;
    @urls = split /\n/, <STDIN>;
}

utf8::decode($_) for(@urls);

die <<USAGE unless @urls;

Pass URLs from argv:

   $0 URL URL...

Or pass URLs from STDIN:

   cat one-url-per-line.txt | $0 -

USAGE

use FindBin;
use lib "$FindBin::Bin/lib";
use Brain;
use Ceis::Extractor;

my $brain = Brain->new;
my $extractor = Ceis::Extractor->new();

my $rel_origin  = $brain->relation("original_of");
my $rel_appear  = $brain->relation("appear_in");
my $rel_precede = $brain->relation("precede");
my $rel_follow  = $brain->relation("follow");

for my $url (@urls) {
    $extractor->url($url);

    my $fulltext = $extractor->fulltext;

    my $k_url      = $brain->blob->add($extractor->url);
    my $k_fulltext = $brain->study($fulltext);

    $brain->relation("original_of")->add($k_fulltext, $k_url);

    say "read: $url";
}
