#!/usr/bin/env perl

use v5.14;
use FindBin;
use lib "$FindBin::Bin/lib";
use utf8;
use Brain;

binmode STDIN, ":utf8";
binmode STDOUT, ":utf8";

my $brain = Brain->new;
while(my $x = <STDIN>) {
    $x =~ s/\n//g;
    next if $x =~ /\A\s*\Z/;

    my $k = $brain->remember($x);

    local $_ = "Remember $k => $x";
    $_ = substr($_, 0, 77) . "..." if length > 80;
    say;
}
