#!/usr/bin/env perl
use strict;
use warnings;
use LWP::UserAgent;
use Mojo::DOM;

my ($url, $selector) = @ARGV;
die "Usage: $0 url css-selecotr" unless $url && $selector;

binmode STDOUT, ":utf8";

my $ua = LWP::UserAgent->new;
my $response = $ua->get($url);

die "Failed to get the URL" unless $response->is_success;
die "The response is not HTML" unless $response->header("Content-Type") =~ m{^text/html\s*(;|$)};

my $dom = Mojo::DOM->new;
$dom->parse($response->decoded_content);

$dom->find($selector)->each(
    sub {
        my $el = shift;
        my $attrs = $el->attr;
        print $el->type . ":\n";
        for (keys %$attrs) {
            print "  " . $_ . ": " . $attrs->{$_} . "\n";
        }
        print "  # " . $el->text;

        print "\n\n";
});
