#!/bin/sh

CPAN_PACKAGE_DETAILS="$HOME/perl5/minicpan/modules/02packages.details.txt.gz"

if [ -f $CPAN_PACKAGE_DETAILS ]; then
    zgrep -i $1 $CPAN_PACKAGE_DETAILS
else
    echo "Missing cpan index: $CPAN_PACKAGE_DETAILS"
fi
