#!/usr/bin/env perl

use v5.14;
use XML::Feed;
use URI;

my @urls = @ARGV;

die "Put urls in ARGV\n"
    unless @urls;

for my $url (@urls) {
    my @feeds = XML::Feed->find_feeds(URI->new($url));
    for (@feeds) {
        my $feed = XML::Feed->parse(URI->new($_));
        say $_->link for $feed->entries;
    }
}
