#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";

use Fe;
my $feedes = Fe->new;
$feedes->namespace("feeds")->index->create(
    settings => {
        number_of_shards => 1,
        number_of_replicas => 0
    }
);
