#!/usr/bin/env perl
use v5.16;
use FindBin;
use lib "$FindBin::Bin/lib";

use Fe;
use Encode qw(encode_utf8 decode_utf8);

my $q = shift @ARGV or die "No q?";

my $fe = Fe->new;
my $domain = $fe->domain("feeds");

my $entries = $domain->view->query(
    text => {
        title => $q,
        content => $q
    }
)->search->as_objects;

binmode STDOUT, ":utf8";

say "Total results: " . $entries->total;

my $i = 1;
while (my $doc = $entries->next) {
   say "# " . $doc->title . "\n  " . $doc->url . "\n";
}
