#!/usr/bin/env perl
use v5.18;use strict;use warnings;
use Digest::SHA;
use File::Next;
use Getopt::Long;

my %opts;
GetOptions(
    \%opts,
    "i=s@",
    "o=s",
);

die "Output file already exists: $opts{o}\n" if -f $opts{o};
open(my $fh_output, ">", $opts{o}) or die $!;

for my $input_dir (@{$opts{i}}) {
    my $files = File::Next::files($input_dir);
    while(defined( my $file = $files->() )) {
        my $digester = Digest::SHA->new("1");

        open my $fh, "<", $file;
        $digester->addfile($fh);
        my $hd = $digester->hexdigest;
        
        close($fh);
        say $fh_output "$hd\t$file";
    }
}
