#!/usr/bin/perl
use strict;
use warnings;

my $cmd = q(git --no-pager log --format='%H %aN <%aE>' --shortstat );

open(GITOUT, "-|", $cmd . join(" ", @ARGV));

my ($commit, $author);

my $commits = {};
my $inserts = {};
my $deletes = {};

while($_ = <GITOUT>) {
    chomp;

    if (/^([0-9a-f]{40}) (.+)$/) {
        $commit = $1;
        $author = $2;
    }
    elsif (/(\d+) insert.* (\d+) delet*/) {

        ($commits->{$author} ||= 0) += 1;
        ($inserts->{$author} ||= 0) += $1;
        ($deletes->{$author} ||= 0) += $2;
    }
}

my @authors = sort {
    $commits->{$b} <=> $commits->{$a} ||
    ($inserts->{$b} + $deletes->{$b}) <=> ($inserts->{$a} + $deletes->{$a})
} keys %$commits;

for my $author (@authors) {
    printf "%7s %7s %7s  %s\n", "±$commits->{$author}", "+$inserts->{$author}", "-$deletes->{$author}", $author;
}
