#!/usr/bin/env perl

use v5.14;
use Google::Search;

$ARGV[0] or die;
my $query = join " ", @ARGV;

my $search = Google::Search->new(
    service => "web",
    query => $query,
    key => "ABQIAAAAm5ncYG25nO-9DBxcnhrfpBSB5gAXNj_QKntvlg9I07k4ds1nChTTzd9a-wwvr9Faqs0_w_7yq-TChQ",
    referrer => "http://gugod.org"
);

for (@{ $search->all }) {
    say $_->title =~ s{</?b>}{}rg;
    say $_->uri;
    say "";
}
