#!/usr/bin/env perl
use strict;
use warnings;

my $number = 1;
for(@ARGV) {
    if (/^ \-([0-9]+) $/x) {
        $number = $1;
    }
}

my $skip = 0;
while (<STDIN>) {
    if ($skip < $number) {
        $skip++;
    } else {
        print;
    }
}

