#!/usr/bin/env perl
use strict;
use warnings;

my $number = ($ARGV[0] && $ARGV[0] =~ /^ \-([1-9][0-9]*) $/x) ? $1 : 1;

my $skip = 0;
<STDIN> while $skip++ < $number;

my $buf;
print $buf while read(STDIN, $buf, 8192);
