#!/usr/bin/env perl
# -*- cperl -*-
use perl5i::2;
use Module::Load;

die "Need module names from arugments.\n" unless @ARGV;

for my $module (@ARGV) {
    try {
        load $module;
        say "$module => @{[$module->VERSION || 0]}";
    } catch {
        my $error = $_;
        say "Failed to load $module: $error";
    }
}
