#!/usr/bin/env perl
# -*- cperl -*-
use v5.14;
use File::Spec;
use File::Find;
use Module::CoreList;
use Module::ExtractUse;
use List::MoreUtils qw(uniq);

my @dir = map { File::Spec->rel2abs($_) } @ARGV;
push @dir, File::Spec->rel2abs(File::Spec->curdir) unless @dir;

my $meu = Module::ExtractUse->new;
my @used = ();
find(
    sub {
        return if $File::Find::dir =~ /\.git/;
        return if $File::Find::dir =~ /\.sv[nk]/;
        return unless -f $File::Find::name;
        $meu->extract_use($File::Find::name);
        push @used, $meu->array;
    },
    @dir
);

say for grep { !$Module::CoreList::version{"$]"}->{$_}  } grep { !/^v?[\.0-9]+$/ } uniq sort @used;
