#!/usr/bin/env perl

use v5.18;
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";
use Fun 'foreach_perl_source_file';

use PPI;
use PPI::Document;
use PPIx::QuoteLike;
my %idx;

my @args = @ARGV;
@args = (".") if !@args;
foreach_perl_source_file \@args => sub {
    my ($file) = @_;
    my $doc = PPI::Document->new($file) or return;
    $doc->index_locations;
    say "... $file";
    my $o;

    $o = $doc->find(sub { $_[1]->isa("PPI::Statement::Package") }) ||[];
    for my $el (@$o) {
        my $n = $el->namespace;
        $idx{$n}{stated}{frequency}++;
        push @{ $idx{$n}{stated}{WHERE} }, [ $file, $el->line_number ];
    }

    $o = $doc->find(sub { $_[1]->isa("PPI::Statement::Include") }) ||[];
    for my $el (@$o) {
        my $n = $el->module;
        $idx{$n}{used}{frequency}++;
        push @{ $idx{$n}{used}{WHERE} }, [ $file, $el->line_number ];
    }
};

for my $tok (keys %idx) {
    next unless $idx{$tok}{stated}{frequency} && ! $idx{$tok}{used}{frequency};
    for my $where (@{$idx{$tok}{stated}{WHERE}}) {
        say join ":", @$where, $tok;
    }
}
