#!/usr/bin/env perl
use v5.18;
use strict;
use warnings;
use Data::Dumper qw'Dumper';
use PPI;
use PPI::Document;

use FindBin;
use lib "$FindBin::Bin/lib";
use Fun::P5 qw(inject_include);

sub main {
    my ($file, $module, @imports) = @_;

    my $doc = PPI::Document->new($file);
    inject_include(
        $doc,
        $module,
        @imports,
    );

    $doc->save($file);
}
main(@ARGV);

