#!/usr/bin/env perl
use strict;
use warnings;

use FindBin qw($Bin);
use lib "$Bin/lib";

use YAML::Tiny qw(LoadFile);
use Getopt::Std;

use PlurkPoster;

my %opts;

getopt('c', \%opts);

die "Usage: $0 -c plurk.yml\n 'Bli blah Hogehoge'" unless $opts{c};

my $config = LoadFile($opts{c}) or die "Fail to load plurk.yml\n";

my $pp = PlurkPoster->new(
    username => $config->{username},
    password => $config->{password},
);

for(@ARGV) {
    $pp->post("!TW $_");
}
