#!/usr/bin/env perl

use strict;
use PPI;
use PPI::Dumper;

use Getopt::Std;

my %opts;
getopts('e:',\%opts);

my $code;
if ( exists $opts{e} ) {
    $code = \"$opts{e}";
} else {
    $code = shift(@ARGV);
    if (!defined($code)) {
        die <<USAGE;
Usage:

   $0 file.pl
   $0 -e '... perl code ...'

USAGE
    }
}

PPI::Dumper->new( PPI::Document->new( $code ) )->print;
