#!/Users/gugod/perl5/perlbrew/perls/perl-5.14.2/bin/perl
#!/usr/bin/env perl
use File::Slurp;
my @words = read_file "/usr/share/dict/words";
print join("", map{chomp;$_} @words[ map { rand(@words) } 1..4 ])."\n";

#!/Users/gugod/perl6/rakudo-star-2012.08/bin/perl6
# slurp("/usr/share/dict/words").split(/\n+/).pick(4).join("").say;

