#!/usr/bin/env perl

use v5.14;
use strict;
use warnings;
use Imager::QRCode;

my $text = shift || die 'text?';
my $qrcode = Imager::QRCode->new();


my $img = $qrcode->plot($text);
$img->write( file => "/tmp/qrcode.png" );

system("open /tmp/qrcode.png");
