#!/usr/bin/env perl
use v5.20;
use HTTP::Tiny;
use JSON::PP qw(decode_json);

my $http = HTTP::Tiny->new;

my $response  = $http->get('http://more.handlino.com/sentences.json?corpus=tweets')
    or die "Unable to get document: $!";

my $x = decode_json($response->{content});

binmode STDOUT, ":utf8";
say $x->{sentences}[0];
