#!/usr/bin/env perl
use common::sense;
use JSON qw(from_json);

use HTTP::Lite;

my $http = HTTP::Lite->new;

my $req  = $http->request('http://more.handlino.com/sentences.json?corpus=tweets')
    or die "Unable to get document: $!";

my $x = from_json($http->body(), { utf8 => 1 });
say $x->{sentences}[0];
