#!/usr/bin/env perl
use v5.14;
use utf8;
binmode STDIN, ":utf8";
binmode STDOUT, ":utf8";

my @urls;
@urls = @ARGV if @ARGV;

if ($urls[0] eq '-') {
    local $/ = undef;
    @urls = split /\n/, <STDIN>;
}

die <<USAGE unless @urls;

Pass URLs from argv:

   $0 URL URL...

Or pass URLs from STDIN:

   cat one-url-per-line.txt | $0 -

USAGE

use FindBin;
use lib "$FindBin::Bin/lib";
use Ceis::Extractor;

for my $url (@urls) {
    my $extractor = Ceis::Extractor->new(url => $url);

    say "$_\n" for $extractor->sentences;
    say "-" x 42 . "\n\n";
}
