#!/usr/bin/env perl
use v5.14;
use Net::Amazon::S3;

unless ($ENV{EC2_ACCESS_KEY} && $ENV{EC2_SECRET_KEY}) {
    die "export env var EC2_ACCESS_KEY and EC2_SECRET_KEY\n";
}

my ($bucket_name, $path) = @ARGV;

unless ($bucket_name && $path) {
    die "Usage: s3fs.pl <bucket> <path>";
}


my $s3 = Net::Amazon::S3->new({
    aws_access_key_id     => $ENV{EC2_ACCESS_KEY},
    aws_secret_access_key => $ENV{EC2_SECRET_KEY},
    retry => 1
});

my $bucket = $s3->bucket($bucket_name);

my $prefix = $path =~ s{^/}{}r =~ s{$}{/}r;
$prefix = "" if $prefix eq "/";

say "### prefix=$prefix";

my $result = $bucket->list({
    prefix => $prefix,
    delimiter => "/"
});

for my $item (@{$result->{keys}}) {
    say $item->{key};
    say "     size=" . $item->{size};
    say "    mtime=" . $item->{last_modified};
}
