#!/usr/bin/env perl

=head1 USAGE

Launch in the command line, put it into background:

    > shoot-myself-every-60s &

Requires the 'convert' program from ImageMagick, and 'imagesnap' program
from http://iharder.net/current/macosx/imagesnap/.

Photos are saved to ~/Pictures/shoot-myself/.

=cut

use strict;
use warnings;
use IO::All;
use 5.010;

while(1) {
    my $time = time;
    my ($day, $month, $year) = (localtime($time))[3, 4, 5];
    $year += 1900;
    $month += 1;
    my $yyyymmdd = sprintf("%04d%02d%02d", $year, $month, $day);

    my $dir = "$ENV{HOME}/Pictures/shoot-myself/$yyyymmdd";
    io->dir($dir)->mkdir unless -d $dir;

    my $file = "$dir/$time";

    system("imagesnap -w 2 -q ${file}.jpg");

    sleep 60;
}
