#!/bin/sh
#! -*- perl -*-
eval 'exec perl -x -wS $0 ${1+"$@"}'
    if 0;

use v5.14;
use FindBin;
use lib "$FindBin::Bin/lib";

use File::Find;
use IO::All -utf8;
use YAML;
use DateTimeX::Easy;
use Text::Xslate;

use Sitebrew;
use Sitebrew::Article;

Sitebrew->initialize(app_root => io->curdir->absolute->name);

my @articles = Sitebrew::Article->all;

my $tx = Text::Xslate->new( input_layer => ":utf8", path => ['views', 'layouts'] );
my $index_html = $tx->render("index.tx", { articles => \@articles });

io("public/index.html")->print($index_html);
