#!/usr/bin/env perl
use v5.14;
use strict;
use warnings;
use File::Find;
use Text::Markdown qw(markdown);
use IO::All -utf8;
use YAML;

sub markdown_file :lvalue {
    state $markdown_file
}

sub html_file {
    markdown_file =~ s/\.md$/.html/r =~ s/^content/public/r;
}

sub build_markdown {
    markdown_file = shift;

    if (-f html_file
        && io(html_file)->mtime > io(markdown_file)->mtime
        && io(html_file)->mtime > io("views/article.tx")->mtime) {
        return;
    }

    system "sitebrew-one", markdown_file;
}

sub build_all {
    find +{
        wanted => sub {
            return if !-f || /\.DS_Store/ || /\.git/ || $File::Find::dir =~ /(sass|\.git)/;

            if (/\.md\z/s) {
                build_markdown($File::Find::name);
            }
            else {
                my $dest = $File::Find::name;
                if ($dest =~ s/^content/public/) {

                    unless ( io->file($dest)->exists && io->file($dest)->mtime > io($_)->mtime ) {
                        say "$File::Find::name => $dest";
                        io($File::Find::name) > io->file($dest)->assert->print("");
                    }
                }
            }
        },
        no_chdir => 1
    }, "content";

    say 'DONE build_all';
}

build_all;
