#!/usr/bin/env perl
#! -*- perl -*-

use v5.14;
use FindBin;
use lib "$FindBin::Bin/lib";

use File::Basename;

use IO::All -utf8;
use Text::Xslate;

use Sitebrew;

my $view_name = @ARGV[0] or die "Usage: @{[ basename($0) ]} view-name\n";

Sitebrew->initialize(app_root => io->curdir->absolute->name);

my $tx = Text::Xslate->new(
    input_layer => ":utf8",
    path => ['views', 'layouts'],
    function => Sitebrew->helpers
);

my $html = $tx->render("${view_name}.tx");

io("public/${view_name}.html")->print($html);

say "BUILD: public/${view_name}.html";
