#!/bin/sh
#! -*- perl -*-
eval 'exec perl -x -wS $0 ${1+"$@"}'
    if 0;

use v5.14;
use utf8;
use FindBin;
use lib "$FindBin::Bin/lib";
use IO::All;
use Sitebrew;
use Sitebrew::Article;

binmode(STDOUT, ":utf8");

Sitebrew->initialize(app_root => io->curdir->absolute->name);
my $brewer = Sitebrew->instance;

my @articles = Sitebrew::Article->all;

for(@articles) {
    say $_->title;
    say "\t", $_->published_at;
    say "\t", $_->href;
    say "\t", $_->content_file;
    say "----";
}

