#!/usr/bin/env perl -w
use strict;
use warnings;
use 5.010;
use AnyEvent::Superfeedr;
use Encode;
use String::Truncate qw(elide);
use YAML;
use Mac::Growl;

die "$0 <jid> <pass>" unless @ARGV >= 2;

my $AppName   = "Superfeedr-Growl";
my $EventType = "Notified";

Mac::Growl::RegisterNotifications($AppName, [ $EventType ], [ $EventType ]);

my $end = AnyEvent->condvar;
my $sf = AnyEvent::Superfeedr->new(
    jid => shift,
    password => shift,
    on_notification => sub {
        my $notification = shift;

        for my $entry ($notification->entries) {
            Mac::Growl::PostNotification(
                $AppName,
                $EventType,
                $entry->title,
                $entry->summary,
                0, 0,
                "/Users/gugod/local/images/superfeddr.png"
            );

            my $dump = {};
            $dump->{$_} = $entry->$_ for qw(title author link content elem ns version);
            say Dump $dump;
            say "----";
        }
    },
);
$end->recv;
