#!/usr/bin/env perl
use v5.18;
use strict;
use warnings;

use Encode qw(encode_utf8);
use Data::Printer;
use List::MoreUtils qw(part);
use Sereal::Decoder;
use Sereal::Encoder;

my %args = @ARGV;
my $input_dir   = $args{'-i'} or die "No input dir -i";

my $srl_decoder = Sereal::Decoder->new;

my @sources = glob($input_dir . "/twitter-timeline-*.srl");

for my $f (@sources) {
    open(my $fh, "<", $f)or die $!;
    local $/ = undef;
    my $d = <$fh>;
    close($fh);

    if ($srl_decoder->looks_like_sereal($d)) {
        my $rows;
        eval {
            $rows = $srl_decoder->decode($d);
            for my $tweet (@$rows) {
                say encode_utf8($tweet->{text});
            }
            1;
        } or do {
            warn "$f is broken";
        };
    } else {
        say STDERR "Does not look like Sereal: $f";
    }
}
