#!/usr/bin/env perl
use v5.14;
use Twitter::API;
use YAML;

my $config = YAML::LoadFile( "$ENV{HOME}/etc/twitter.yml" );

my $twitter = Twitter::API->new(
    consumer_key    => $config->{consumer_key},
    consumer_secret => $config->{consumer_secret}
);

my $o = $twitter->oauth_request_token;

my $url = $twitter->oauth_authorization_url({ "oauth_token" => $o->{"oauth_token"} });

say "open $url";

system "open" => $url;

print "Enter the PIN#\n";

my $pin = <STDIN>;
chomp($pin);

my $p = $twitter->oauth_access_token({
    "token" => $o->{"oauth_token"},
    "token_secret" => $o->{"oauth_token_secret"},
    "verifier" => $pin,
});

say "access_token: " . $p->{"oauth_token"};
say "access_token_secret: " . $p->{"oauth_token_secret"};
