#!/bin/sh

yes | aptitude install screen vim emacs23-nox git-core build-essential zlib1g-dev libssl-dev

# Install Ruby Enterprise Edition
if [ ! -e /usr/local/bin/ruby ]; then
    wget http://rubyforge.org/frs/download.php/66164/ruby-enterprise_1.8.7-2009.10_i386.deb
    dpkg -i ruby-enterprise_1.8.7-2009.10_i386.deb
fi

# Update system gem if necessary
if [ `gem -v` != "1.3.5" ]; then
    gem update --system
    gem update
fi

# Install Nginx w/ Passenger
if [ ! -e /opt/nginx/sbin/nginx ]; then
    echo -e "\n1\n\n" | passenger-install-nginx-module
fi

# Create the user for rails apps
if [ ! -d /home/apps ]; then
    yes | adduser --quiet --disabled-password --disabled-login apps
fi
