#!/bin/sh

# This step ask you to give a password for mysql root account.
yes | aptitude install mysql-server-5.1 mysql-client-5.1 

yes | aptitude install curl screen vim emacs23-nox git-core build-essential zlib1g-dev libssl-dev libreadline5-dev imagemagick libmagickcore-dev libmagickwand-dev libxapian-dev libxapian15 xapian-tools

# Install Ruby Enterprise Edition
if [ ! -e /usr/local/bin/ruby ]; then
    wget http://rubyforge.org/frs/download.php/66164/ruby-enterprise_1.8.7-2009.10_i386.deb
    dpkg -i ruby-enterprise_1.8.7-2009.10_i386.deb
fi

# Update system gem if necessary
if [ `gem -v` != "1.3.5" ]; then
    gem update --system
    gem update
fi

# Use the latest passenger (2.2.8) and nginx (0.7.64)
if [ ! -d /usr/local/lib/ruby/gems/1.8/gems/passenger-2.2.8 ]; then
    gem install passenger -v=2.2.8 --no-ri --no-rdoc
fi

# Install Nginx w/ Passenger. SSL-enabled.
if [ ! -e /opt/nginx/sbin/nginx ]; then
    wget -O /tmp/nginx-0.7.64.tar.gz http://sysoev.ru/nginx/nginx-0.7.64.tar.gz

    cd /tmp
    tar xzf nginx-0.7.64.tar.gz
    cd -

    echo -e "\n2\n/tmp/nginx-0.7.64\n\n--with-http_ssl_module\n\n\n" | passenger-install-nginx-module
fi

if [ ! -e /etc/init.d/nginx ]; then
    curl http://github.com/jnstq/rails-nginx-passenger-ubuntu/raw/master/nginx/nginx > /etc/init.d/nginx
    chmod +x /etc/init.d/nginx
fi

# Create the user for rails apps
if [ ! -d /home/apps ]; then
    yes | adduser --quiet --disabled-password apps
fi

# Install massive number of ruby gems
if [ ! -f /home/apps/.gems_installed ]; then
    gem source -a http://gemcutter.org
    gem source -a http://gems.github.com

    gem install --no-ri --no-rdoc rmagick 
    gem install --no-ri --no-rdoc ar_mailer sinatra datamapper do_sqlite3 do_mysql xspond-xapian-ruby ZenTest rspec rspec-rails factory_girl cucumber
    gem install --no-ri --no-rdoc rails -v=2.3.5

    gem list --local > /home/apps/.gems_installed
fi
