#!/usr/bin/env perl
use v5.14;

use Encode qw(encode_utf8);
use Mojo::DOM;
use Mojo::UserAgent;
use Mojo::JSON qw(encode_json);

my ($url, $query, $out) = @ARGV;
die "Need url and query" unless $url && $query;

my $ua = Mojo::UserAgent->new;
$ua->max_redirects(5);

my $i = 0;
$ua->get($url)->res->dom($query)->each(
    sub {
        $i++;
        local $_ = $_[0];

        if ($out) {
            eval "$out";
        }
        else {
            say encode_utf8(join ", ", $_->all_text, $_->type, encode_json($_->attr));
        }
    }
);
