#!/usr/bin/env perl
use v5.14;
exit unless $ENV{HOME};

use FindBin;
use lib "$FindBin::Bin/lib";
use VideoOrganizer;

my $root = shift @ARGV
    or die "Usage: $0 <Videos Folder>\n";
my $vo = VideoOrganizer->new(root => $root);
$vo->run;

