#!/usr/bin/env perl

use strict;
use warnings;


use Text::CSV;
use Spreadsheet::ParseExcel;

my $csv = Text::CSV->new({binary=>1});

my $parser   = Spreadsheet::ParseExcel->new();
my $workbook = $parser->parse( $ARGV[0] );

if ( !defined $workbook ) {
    die $parser->error(), ".\n";
}

for my $worksheet ( $workbook->worksheets() ) {

    my ( $row_min, $row_max ) = $worksheet->row_range();
    my ( $col_min, $col_max ) = $worksheet->col_range();

    for my $row ( $row_min .. $row_max ) {
        my @line;

        for my $col ( $col_min .. $col_max ) {

            my $cell = $worksheet->get_cell( $row, $col );
            next unless $cell;
            push @line, $cell->unformatted;
        }

        $csv->combine(@line);
        print $csv->string . "\n";
    }
}
