#!/usr/bin/env perl
use v5.18;
use URI;
use XML::Feed;
use Encode;

my $url = shift(@ARGV) or exit 0;
my $feed = XML::Feed->parse(URI->new($url)) or exit 0;

for my $entry ($feed->entries) {
    my $str = join "\t", map { s/\s+/ /; $_ } (
        $entry->title,
        $entry->link
    );

    $str = Encode::is_utf8($str) ? Encode::encode_utf8($str) : $str;
    say $str;
}
